### ISSUE TITLE
Improve apparmor state

### ISSUE THREAD

**Issue by rjfd** [SUSE/ceph-salt-formula#4]
Currently the apparmor state is not doing much. We should check what was being done in DeepSea (https://github.com/SUSE/DeepSea/tree/master/srv/salt/ceph/apparmor) and add those things to ceph-salt formula.

Also, we need to check what [cephadm](https://github.com/ceph/ceph/blob/master/src/cephadm/cephadm)  is doing in this regard, and make sure that what ceph-salt formula preforms is compatible with cephadm.

**Comment by ricardoasmarques** [comment]
Moved to https://github.com/SUSE/ceph-bootstrap/issues/12
