### ISSUE TITLE
Use jinja macros to access the pillar data

### ISSUE THREAD

**Issue by rjfd** [SUSE/ceph-salt-formula#5]
There is a lot of duplicate code to fetch data from the pillar, specially due to all the handling of non-existent keys in the pillar. 

The objective is to create some jinja macros that can be used to reduce the amount of duplicate code.

See https://jinja.palletsprojects.com/en/2.10.x/templates/#macros

**Comment by ricardoasmarques** [comment]
Moved to https://github.com/SUSE/ceph-bootstrap/issues/29
